config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => "deals#index" 

  resources :deals

  resources :categories

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :deals

  # validations
	validates_presence_of   :name
	validates_uniqueness_of :slug    # uniq also at database level

	extend FriendlyId
  friendly_id :name, use: :slugged

  mount_uploader :photo_url, ImageUploader
end

app/models/deal.rb
class Deal < ActiveRecord::Base

  belongs_to :category, :counter_cache => true

  # validations
  validates_presence_of   :title, :deal_url
  validates_uniqueness_of :slug    # uniq also at database level

  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :photo_url, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_page

  def current_page
    @page ||= params[:page].blank? ? 1 : params[:page].to_i
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

  def index
    per_page = 16
    @categories = Category.all
    @category = Category.friendly.find_by_slug(params[:catogory]) if params[:catogory].present? && params[:catogory] != 'all'
    @deals = @category.deals.where(:deal_valid => true).order('id desc').paginate(:page => current_page, :per_page => per_page) if @category
    @deals ||= Deal.includes(:category).where(:deal_valid => true).order('id desc').paginate(:page => current_page, :per_page => per_page)
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_deals.html.erb
<% deals.each do |d| %>
  <div class="deals_container_item">
    <div class="deals_container_item_title"><%= truncate(d.title, length: 30) %></div>
    <%= image_tag(d.photo_url , :class => "deals_container_item_img" )%>
    <div class="deals_container_item_description">
      <%= truncate(d.description, length: 80) %>
    </div>  
    <div class="deals_container_item_price">
      @ Rs. <%= d.discount_price %>
      <% off = (d.price*1.0 - d.discount_price)/d.price*100 %>
      <span class="deals_container_item_real_price"> Rs. <%= d.price %> <%= "(#{off.round}% off)" %></span>
    </div>
    <div align="center" class="deals_container_item_deal_url_div">
      <div>
         <a href="<%= d.deal_url %>" target= "_blank" class="deals_container_item_deal_url" >BUY</a>
      </div>
    </div>
  </div>
<% end %>

app/views/deals/index.html.erb
<div class="main_container">
  <div class="categories_container">
    <div class="logo">
      <%= link_to image_tag('logo.jpg', :width => '150px', :height => '120px'), root_path %>
    </div>
    <span class="categories_container_item"><%= link_to "All", deals_path( :catogory => "all") %></span>
    <% @categories.each do |c| %>
      <span class="categories_container_item"><%= link_to c.name.capitalize, deals_path(:catogory => c.slug) %></span>
    <% end %>
  </div>
  <br>
  <div class="deals_container">
    <div class="deals_container_header" >
      <% if @category %>
        <div><%= "#{@category.name.capitalize} Deals"  %></div>
      <% else %>
        <div>All Deals</div>
      <% end %>
    </div>
    <br><br>
    <%= render 'deals' , :deals => @deals %>
  </div>
  <div class="view_more_class" align="center"><%= link_to "View More",deals_path(:page => @page + 1 ), :remote => true  %></div>

</div>

app/views/deals/index.js.erb
<% if !@deals.blank? %>
  $('.deals_container').append("<%= escape_javascript(render 'deals', :deals => @deals) %>");
  $('.view_more_class').empty().append('<%= link_to "View More",deals_path(:page => @page + 1 ), :remote => true  %>');
<% else %>
  $('.view_more_class').empty();
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Deal Duniya | Deals and Coupon site</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="<%= asset_path('logo.jpg') %>" rel="shortcut icon"></link>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<div>
  <hr>
  <center></center>
</div>
</body>
</html>